[build]
  command = "npm run build"
  publish = "build"   # ou "dist" se usares Vite

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  DISABLE_ESLINT_PLUGIN = "true"